version: '3.8'

services:
  ros2-bridge:
    build:
      context: ../ros2_ws
      dockerfile: Dockerfile
    container_name: open-teleop-ros2-bridge
    volumes:
      - ../ros2_ws:/ros2_ws
    networks:
      - teleop-network
    environment:
      - ROS_DOMAIN_ID=42
      - ROBOT_ID=robot1
      - CONTROLLER_ADDRESS=controller:8080
      - ZMQ_PORT=5555
    # Uncomment to use a robot simulator
    # depends_on:
    #   - robot-simulator

  controller:
    build:
      context: ../controller
      dockerfile: Dockerfile
    container_name: open-teleop-controller
    ports:
      - "8080:8080"  # HTTP server
      - "8443:8443"  # HTTPS server (for production)
      - "8888:8888"  # WebRTC signaling
      - "5555:5555"  # ZeroMQ communication
    volumes:
      - ../controller:/app
    networks:
      - teleop-network
    depends_on:
      - ros2-bridge
    environment:
      - ROS_BRIDGE_HOST=ros2-bridge
      - PORT=8080
      - WEBRTC_PORT=8888
      - ZMQ_ADDRESS=tcp://*:5555

networks:
  teleop-network:
    driver: bridge

# For future use with persistent data
# volumes:
#   teleop-data: 