// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package diagnostic

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Memory struct {
	_tab flatbuffers.Table
}

func GetRootAsMemory(buf []byte, offset flatbuffers.UOffsetT) *Memory {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Memory{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMemory(buf []byte, offset flatbuffers.UOffsetT) *Memory {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Memory{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Memory) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Memory) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Memory) TotalMb() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Memory) MutateTotalMb(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *Memory) UsedMb() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Memory) MutateUsedMb(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *Memory) AvailableMb() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Memory) MutateAvailableMb(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *Memory) UsedPercent() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Memory) MutateUsedPercent(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *Memory) AvailablePercent() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Memory) MutateAvailablePercent(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func MemoryStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MemoryAddTotalMb(builder *flatbuffers.Builder, totalMb float32) {
	builder.PrependFloat32Slot(0, totalMb, 0.0)
}
func MemoryAddUsedMb(builder *flatbuffers.Builder, usedMb float32) {
	builder.PrependFloat32Slot(1, usedMb, 0.0)
}
func MemoryAddAvailableMb(builder *flatbuffers.Builder, availableMb float32) {
	builder.PrependFloat32Slot(2, availableMb, 0.0)
}
func MemoryAddUsedPercent(builder *flatbuffers.Builder, usedPercent float32) {
	builder.PrependFloat32Slot(3, usedPercent, 0.0)
}
func MemoryAddAvailablePercent(builder *flatbuffers.Builder, availablePercent float32) {
	builder.PrependFloat32Slot(4, availablePercent, 0.0)
}
func MemoryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
