# Controller Configuration - DEVELOPMENT Environment
version: "1.0"
config_id: "2e8f7a4d-6c01-4bb8-9e4a-8e72f9a5a9f1"
lastUpdated: "2025-03-16T10:00:00Z"
environment: "development"

# ZeroMQ Settings - Development
zeromq:
  # In development, bind to localhost only
  receiver_address: "tcp://localhost:5555"
  publisher_address: "tcp://localhost:5556"
  message_queue_size: 1000
  timeout_ms: 1000

# HTTP API Server Settings - Development
server:
  port: 8080
  request_timeout: 30
  max_request_size: 10

# Message Processing Settings - Development (fewer workers for local testing)
processing:
  high_priority_workers: 2
  standard_priority_workers: 1
  low_priority_workers: 1 