# Controller Configuration - PRODUCTION Environment
version: "1.0"
config_id: "2e8f7a4d-6c01-4bb8-9e4a-8e72f9a5a9f1"
lastUpdated: "2025-03-16T10:00:00Z"
environment: "production"

# ZeroMQ Settings - Production
zeromq:
  # In production, accept connections from any interface
  receiver_address: "tcp://*:5555"
  publisher_address: "tcp://*:5556"
  message_queue_size: 5000  # Increased queue size for production
  timeout_ms: 2000  # Increased timeout for production

# HTTP API Server Settings - Production
server:
  port: 8080
  request_timeout: 60  # Increased timeout for production
  max_request_size: 20  # Increased max request size for production

# Message Processing Settings - Production (full worker count)
processing:
  high_priority_workers: 8
  standard_priority_workers: 4
  low_priority_workers: 2 