# Controller Configuration
version: "1.0"
config_id: "2e8f7a4d-6c01-4bb8-9e4a-8e72f9a5a9f1"
lastUpdated: "2025-03-16T10:00:00Z"

# ZeroMQ Settings
zeromq:
  # Address to bind for receiving messages from gateways
  # Format: transport://interface:port
  # Example: tcp://*:5555 binds to all interfaces on port 5555
  receiver_address: "tcp://*:5555"
  
  # Address to bind for publishing messages to gateways
  # Format: transport://interface:port
  # Example: tcp://*:5556 binds to all interfaces on port 5556
  publisher_address: "tcp://*:5556"
  
  # Message queue size for incoming/outgoing messages
  message_queue_size: 1000
  
  # Timeout in milliseconds for message operations
  timeout_ms: 1000

# HTTP API Server Settings
server:
  # Port to listen on for HTTP API requests
  port: 8080
  
  # Request timeout in seconds
  request_timeout: 30
  
  # Maximum allowed request size in MB
  max_request_size: 10

# Message Processing Settings
processing:
  # Number of worker goroutines for high priority messages
  high_priority_workers: 4
  
  # Number of worker goroutines for standard priority messages
  standard_priority_workers: 2
  
  # Number of worker goroutines for low priority messages
  low_priority_workers: 1 