# Gateway Configuration - This represents what the controller would send to the gateway
# (A subset of the full system configuration)
version: "1.0"
config_id: "3f7ac68a-7e3a-4d4b-b9d6-5d0b267e5e8c"
lastUpdated: "2025-03-16T10:00:00Z"
robot_id: "d290f1ee-6c54-4b01-90e6-d701748f0851"

# Topic mappings configuration
topic_mappings:
  # Sensor data (OUTBOUND - from ROS to controller)
  - ros_topic: "/battery_state"
    ott: "teleop.sensor.battery"
    priority: "STANDARD"
    message_type: "sensor_msgs/msg/BatteryState"
    direction: "OUTBOUND"
    source_type: "ROS2_CDM"
  
  # Robot control (INBOUND - from controller to ROS)
  - ros_topic: "/cmd_vel"
    ott: "teleop.control.velocity"
    priority: "HIGH"
    message_type: "geometry_msgs/msg/Twist"
    direction: "INBOUND"
    source_type: "ROS2_CDM"
    
  # System metrics (custom Open-Teleop defined message)
  - ott: "teleop.diagnostic.system_metrics"
    priority: "LOW"
    source_type: "OPEN_TELEOP"
    direction: "OUTBOUND"

# Default settings for topics
defaults:
  priority: "STANDARD"
  direction: "OUTBOUND"
  source_type: "ROS2_CDM"

# Gateway behavior settings
settings:
  # Buffer and reconnection settings
  message_buffer_size: 1000
  reconnect_interval_ms: 1000
  
  # Optional throttling settings per priority level (0 = no throttling)
  throttle_rates:
    high_hz: 0
    standard_hz: 10
    low_hz: 1 