# Unified Open-Teleop Configuration
version: "1.0"
config_id: "unified-config-2025-03-17"
lastUpdated: "2025-03-17T00:00:00Z"
robot_id: "d290f1ee-6c54-4b01-90e6-d701748f0851"

# Topic mappings configuration
topic_mappings:
  # Sensor data (OUTBOUND - from ROS to controller)
  - ros_topic: "/batterystate"
    ott: "teleop.sensor.battery"
    priority: "STANDARD"
    message_type: "sensor_msgs/msg/BatteryState"
    direction: "OUTBOUND"
    source_type: "ROS2_CDR"
  
  - ros_topic: "/image"
    ott: "teleop.sensor.image"
    priority: "STANDARD"
    message_type: "sensor_msgs/msg/Image"
    direction: "OUTBOUND"
    source_type: "ROS2_CDR"

  - ros_topic: "/string"
    ott: "teleop.status"
    priority: "STANDARD"
    message_type: "std_msgs/msg/String"
    direction: "OUTBOUND"
    source_type: "ROS2_CDR"

  # Robot control (INBOUND - from controller to ROS)
  - ros_topic: "/cmd_vel"
    ott: "teleop.control.velocity"
    priority: "HIGH"
    message_type: "geometry_msgs/msg/Twist"
    direction: "INBOUND"
    source_type: "ROS2_CDR"

# Default settings for topics
defaults:
  priority: "STANDARD"
  direction: "OUTBOUND"
  source_type: "ROS2_CDR"

# Throttling settings per priority level (0 = no throttling)
throttle_rates:
  high_hz: 0
  standard_hz: 10
  low_hz: 1 