# Test Open-Teleop Configuration with AV Integration
version: "1.0"
config_id: "av-test-config-2025-05-24"
lastUpdated: "2025-05-04T00:00:00Z"
robot_id: "d290f1ee-6c54-4b01-90e6-d701748f0851"

# Default settings for topics
defaults:
  priority: "STANDARD"
  direction: "OUTBOUND"
  source_type: "ROS2_CDR"

# ROS topic mappings  
topic_mappings:
  - ros_topic: "/robot/battery_state"
    ott: "teleop.sensor.battery_state"
    topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0001"
    message_type: "sensor_msgs/msg/BatteryState"
    priority: "LOW"
  
  - ros_topic: "/string"
    ott: "teleop.status"
    topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0002"
    priority: "STANDARD"
    message_type: "std_msgs/msg/String"
    direction: "OUTBOUND"
    source_type: "ROS2_CDR"

  - ros_topic: "/robot/odom"
    ott: "teleop.sensor.odometry"
    topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0003"
    message_type: "nav_msgs/msg/Odometry"
    priority: "STANDARD"
  
  - ros_topic: "/robot/cmd_vel"
    ott: "teleop.control.velocity"
    topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0004"
    message_type: "geometry_msgs/msg/Twist"
    direction: "INBOUND"
    priority: "HIGH"

  # AV stream configurations
  - ros_topic: "/camera/image_raw"
    ott: "teleop.video.main_camera"
    topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0005"
    message_type: "sensor_msgs/msg/Image"
    encoder_params:
      encoding_format: "video/h264"
      width: 640
      height: 480
      framerate: 30
      bitrate: 2000 # kbps
      gop_size: 30
    direction: "OUTBOUND"
    priority: "HIGH"
  
  - ros_topic: "/robot/depth_camera/image_raw"
    ott: "teleop.video.depth_camera"
    topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0006"
    message_type: "sensor_msgs/msg/Image"
    encoder_params:
      encoding_format: "video/h264"
      width: 640
      height: 480
      framerate: 15 # Depth cams often lower FPS
      bitrate: 1000 # kbps
      gop_size: 30 # frames
    direction: "OUTBOUND"
    priority: "STANDARD"

# Media Gateway mappings (hardware devices -> Open Teleop protocol)
media_mappings:
  video:
    - device_id: "video0"
      ott: "teleop.video.navigation_camera"
      topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0007"
      encoding_format: "video/h264"
      encoder_params:
        width: 1280
        height: 720
        framerate: 30
        bitrate: 4000
        gop_size: 15
        profile: "baseline"
        preset: "ultrafast"
      direction: "OUTBOUND"
      priority: "HIGH"

  audio:
    - device_id: "audio0"
      ott: "teleop.audio.main_microphone"
      topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0010"
      encoding_format: "audio/opus"
      encoder_params:
        bitrate: 64000
        sample_rate: 48000
        channels: 1
      priority: "STANDARD"
    
    - device_id: "audio1"
      ott: "teleop.audio.ambient_microphone"
      topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0011"
      encoding_format: "audio/opus"
      encoder_params:
        bitrate: 32000
        sample_rate: 48000
        channels: 1
      priority: "LOW"

# Media Gateway configuration
media_gateway:
  device_discovery:
    enabled: true
    topic: "teleop.media.available_sources"
    topic_id: "f0000001-aaaa-bbbb-cccc-d701748f0012"
    direction: "OUTBOUND"
    priority: "LOW"
    check_interval_seconds: 10

# Throttling settings per priority level (0 = no throttling)
throttle_rates:
  high_hz: 0
  standard_hz: 10
  low_hz: 1

# ZMQ settings
zeromq:
  controller_address: "tcp://127.0.0.1:5555"
  publish_address: "tcp://127.0.0.1:5556"
  message_buffer_size: 1000
  reconnect_interval_ms: 1000

# Controller settings
controller:
  server:
    port: 8080
    request_timeout: 5000
    max_request_size: 10485760 