# config/gateway-config.yaml
# Bootstrap configuration for the ROS Gateway

gateway:
  # ZeroMQ configuration for connecting to the controller
  zmq:
    controller_address: "tcp://localhost:5555"
    publish_address: "tcp://*:5556"
    message_buffer_size: 1000
    reconnect_interval_ms: 1000
    
  # Default direction is OUTBOUND (from ROS to controller) if not specified
  defaults:
    priority: "STANDARD"
    direction: "OUTBOUND"
    
  # Logger configuration
  logging:
    level: "DEBUG"
    log_to_file: true
    log_path: "/teleop_data/logs/ros_gateway"
    log_rotation_days: 7 

# Optional: Add any other gateway-specific operational settings here
# e.g., processing queue sizes if not derived from teleop config
